# Generated by Django 6.0.4 on 2026-04-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_buyingguide_author_news_author_review_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingguide',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='core.brand'),
        ),
        migrations.AddField(
            model_name='news',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='core.brand'),
        ),
        migrations.AddField(
            model_name='review',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.brand'),
        ),
        migrations.AddField(
            model_name='solution',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='core.brand'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Leave blank for direct deal', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deal', models.BooleanField(default=False, help_text='Check if this is a direct discount deal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.brand')),
            ],
        ),
    ]
