# Generated by Django 6.0.4 on 2026-04-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_buyingguide_brand_news_brand_review_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='display_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Display size in inches', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='gpu_type',
            field=models.CharField(blank=True, help_text='e.g. RTX 4060, Iris Xe', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_type',
            field=models.CharField(blank=True, help_text='e.g. Core i7, Ryzen 7', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram_gb',
            field=models.IntegerField(blank=True, help_text='RAM capacity in GB', null=True),
        ),
    ]
