# Generated by Django 6.0.4 on 2026-04-12 05:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_laptop_display_size_laptop_gpu_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Brand overview and history for SEO'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
