# Generated by Django 6.0.4 on 2026-04-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('budget_range', models.CharField(choices=[('under_500', 'Under $500'), ('500_1000', '$500 - $1000'), ('1000_1500', '$1000 - $1500'), ('over_1500', 'Above $1500')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
