# Generated by Django 6.0.4 on 2026-04-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='interest_type',
            field=models.CharField(choices=[('DEALS', 'Deals & Price Drops'), ('NEWS', 'Tech News'), ('REVIEWS', 'Expert Reviews'), ('ALL', 'Everything')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.laptop'),
        ),
    ]
