# Generated by Django 6.0.4 on 2026-04-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingguideitem',
            name='ordering',
            field=models.IntegerField(choices=[(1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9'), (10, 'Rank 10'), (11, 'Rank 11'), (12, 'Rank 12'), (13, 'Rank 13'), (14, 'Rank 14'), (15, 'Rank 15'), (16, 'Rank 16'), (17, 'Rank 17'), (18, 'Rank 18'), (19, 'Rank 19'), (20, 'Rank 20')], default=1, help_text='Select Rank (1 is Best)'),
        ),
    ]
