# Generated by Django 6.0.4 on 2026-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_buyingguideitem_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(default='subscriber@phoneradar.in', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='budget_range',
            field=models.CharField(choices=[('under_50k', 'Under ₹50,000'), ('50k_100k', '₹50,000 - ₹1,00,000'), ('100k_150k', '₹1,00,000 - ₹1,50,000'), ('over_150k', 'Above ₹1,50,000')], max_length=20),
        ),
    ]
